[project]
name = "products-code-qa-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.139.0",
    "pandas>=3.0.3",
    "torch>=2.13.0",
    "transformers>=5.13.0",
    "uvicorn[standard]>=0.51.0",
]

[project.scripts]
products-code-qa-bot = "products_code_qa_bot:main"

[build-system]
requires = ["uv_build>=0.11.25,<0.12.0"]
build-backend = "uv_build"
