[project]
name = "products-code-qa-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "pandas>=3.0.3",
    "pytesseract>=0.3.13",
    "torch>=2.13.0",
    "transformers>=5.13.0",
    "paddleocr[doc-parser]>=3.7.0",
    "paddlepaddle>=3.3.1",
    "opencv-python>=4.10.0",
]

[project.scripts]
products-code-qa-bot = "products_code_qa_bot:main"

[build-system]
requires = ["uv_build>=0.11.25,<0.12.0"]
build-backend = "uv_build"
